### ISSUE TITLE
Plugins directory (/usr/lib/trino/plugin) is overwritten on the workers

### ISSUE THREAD

**Issue by fxulusoy** [valeriano-manassero/helm-charts#64]
Latest PR is overwriting the `/usr/lib/trino/plugin` directory. Then the workers cannot start and they throw the following exception:
```
2021-06-21T09:02:26.916Z	INFO	main	io.trino.metadata.StaticCatalogStore	-- Loading catalog etc/catalog/mydb.properties --
2021-06-21T09:02:26.917Z	ERROR	main	io.trino.server.Server	No factory for connector 'postgresql'.  Available factories: [system]
java.lang.IllegalArgumentException: No factory for connector 'postgresql'.  Available factories: [system]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:443)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:193)
	at io.trino.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
	at io.trino.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at io.trino.server.Server.doStart(Server.java:123)
	at io.trino.server.Server.lambda$start$0(Server.java:77)
	at io.trino.$gen.Trino_355____20210621_090218_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:77)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
```
When I look into `/usr/lib/trino/plugin` directory in the worker nodes, they are empty. 

This is because of this change:
https://github.com/valeriano-manassero/helm-charts/pull/63/files#diff-e3373e8a8249f23c11d4180d8387fabbdc9358dd07a3e590b095b47818ece898R56

**Comment by valeriano-manassero** [comment]
Ok, I'm going to create a PR very soon, sorry for the mistake.

**Comment by valeriano-manassero** [comment]
@fxulusoy can you pls review #65 ?
